# Generated by Django 4.0.5 on 2022-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='kind',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition')], max_length=20, verbose_name='전문 분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not Specified'), ('female', 'Female')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
