# Generated by Django 4.0.5 on 2022-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
