# Generated by Django 4.0.5 on 2022-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bind_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='kind',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('fitness', 'Fitness')], max_length=20, verbose_name='전문 분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not Specified'), ('female', 'Female')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
