# Generated by Django 4.0.5 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_user_approved_user_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='approved_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('not-specified', 'Not Specified')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
