# Generated by Django 4.0.5 on 2022-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_coach_approved_coach_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not Specified'), ('female', 'Female')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
