# Generated by Django 4.0.5 on 2022-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_coach_kind_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='kind',
            field=models.CharField(choices=[('nutrition', 'Nutrition'), ('fitness', 'Fitness')], max_length=20, verbose_name='전문 분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-specified', 'Not Specified'), ('male', 'Male')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
