# Generated by Django 4.0.5 on 2022-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_coach_kind_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('male', 'Male'), ('female', 'Female')], max_length=80, null=True, verbose_name='성별'),
        ),
    ]
