# Generated by Django 4.0.5 on 2022-06-27 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0002_remove_cart_quantioty_cart_quantity_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='kind',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('food', 'Food')], max_length=20, verbose_name='종류'),
        ),
    ]
