# Generated by Django 4.0.5 on 2022-06-27 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0003_alter_product_user_alter_productcategory_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='name',
        ),
        migrations.AddField(
            model_name='routine',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='수량'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='productapp.productcategory', verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='kind',
            field=models.CharField(choices=[('food', 'Food'), ('exercise', 'Exercise')], max_length=20, verbose_name='종류'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='challenge',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.routine', verbose_name='루틴'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
