# Generated by Django 4.0.5 on 2022-07-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_remove_productcategory_name_challenge_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='bind_number',
            field=models.IntegerField(null=True),
        ),
    ]
