# Generated by Django 4.0.5 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_challenge_bind_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='kind',
            field=models.CharField(choices=[('food', 'Food'), ('exercise', 'Exercise')], max_length=20, verbose_name='종류'),
        ),
    ]
