# Generated by Django 4.0.5 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_alter_productcategory_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='kind',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('food', 'Food')], max_length=20, verbose_name='종류'),
        ),
    ]
