# Generated by Django 4.0.5 on 2022-07-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_alter_productcategory_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='routine',
        ),
        migrations.AddField(
            model_name='challenge',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.product', verbose_name='루틴'),
        ),
    ]
