# Generated by Django 4.0.5 on 2022-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0003_alter_boardcategory_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcategory',
            name='kind',
            field=models.CharField(choices=[('notice', 'Notice'), ('free', 'Free')], max_length=20, verbose_name='종류'),
        ),
    ]
